CREATE TABLE IF NOT EXISTS schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(20) NOT NULL DEFAULT 'study',
  title VARCHAR(255) NOT NULL,
  class_name VARCHAR(100) NOT NULL,
  subject_name VARCHAR(255) DEFAULT NULL,
  schedule_date DATE NOT NULL,
  schedule_time VARCHAR(20) NOT NULL,
  room VARCHAR(100) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
